import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="w-full border-b-2 border-blue-500 flex gap-4 justify-between">
          <div className="flex gap-4">
            <Link href="/primary">
              <button className="border-2 border-white">Example 1</button>
            </Link>
            <Link href="/secondary">
              <button className="border-2 border-white">Example 2</button>
            </Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
